version: '3.0'

services:
  crud-service:
    container_name: crud-service
    build:
      context: ./crud-service/
    environment:
    - MONGODB_URI=mongodb://mongodb:27017/todo
    ports:
      - 3000:3000
      - 9229:9229
    depends_on: 
      - mongodb
    volumes:
      - ./crud-service/:/app
    command: npm run debug


  mongodb:
    hostname: mongodb
    container_name: mongodb
    image: mongo:latest
    environment:
      - MONGO_INITDB_DATABASE=todo
    ports:
      - 27017:27017

  ch1_java:
    image: basic_docker_ch1:java
    ports:
      - 8080:8080
  
  ch2_java:
    image: basic_docker_ch2:java
    ports:
      - 8081:8080
