version: '3.9'

services:
  todo-service:
    container_name: todo-service
    hostname: todo-service
    image: todo_service
    environment:
    - MONGODB_URI=mongodb://mongodb:27017/todo
    ports:
      - 8080:3000
    depends_on: 
      - mongodb
    deploy:
      restart_policy:
        condition: any
    

  other-service:
    container_name: other-service
    image: other_service
    environment:
    - CRUD_SERVICE_URL=http://todo-service:3000
    ports:
      - 4000:4000
    depends_on: 
      - todo-service
    deploy:
      restart_policy:
        condition: any


  mongodb:
    hostname: mongodb
    container_name: mongodb
    image: mongo:latest
    environment:
      - MONGO_INITDB_DATABASE=todo
    ports:
      - 27017:27017
    # volumes:
    #   - ./mongo-volume:/data/db
